### ISSUE TITLE
Unify namespaces in CDP4Composition.Composition directory and make sure correct BooleanToVisibilityConverter is being used

### ISSUE THREAD

**Issue by jan-at-rhea** [STARIONGROUP/COMET-IME-Community-Edition#1164]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
CDP4Composition.Composition directory has mixed namespaces (of CDP4Composition.Composition and just CDP4Composition), this has to be corrected.
In some files in XAML, instead of CDP4 BooleanToVisibilityConverter, the standard one is used (because of the mixed namespace). Since .net Standard and .net 6 doesn't have BooleanToVisibilityConverter it will block the migration and has to be addressed.

### Steps to Reproduce
Navigate to CDP4Composition.Composition and check the namespaces.
Set a breakpoint in Convert of BooleanToVisibilityConverter and observe that it isn't hit in all scenarios.

- COMET version:
  - [ ] COMET-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4/COMET Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [x] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by lxatrhea** [comment]
@samatrhea What do you think about this one?
