### ISSUE TITLE
IME disappearing while working in model - following publication of state dependent parameters

### ISSUE THREAD

**Issue by MartinFijneman** [STARIONGROUP/COMET-IME-Community-Edition#1180]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the COMET-IME
- [ ] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

not yet exactly reproducible, but already happend 2 or 3 times:

Comet IME disappearing, no error message.

### Steps to Reproduce

on the EPC server, setting up the SWBS template model

- logged and open model, representing domain Armaments
- open ED browser, publication browser
- use search to look for parameters for "power"
- use filter to see only ARM domain
- provide values for state dependent parameters peak and mean power consumption
- publish values

### Logs

  - [ ] There are no logs regarding the issue
  - [X] I have attached a log file or included the relevant section in this issue  
  
[CDP4IME - Crash after publication of state dependent parameters from Armament domain.log](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/files/10105752/CDP4IME.-.Crash.after.publication.of.state.dependent.parameters.from.Armament.domain.log)

[CDP4IME - v2 Crash after publication of state dependent parameters from Armament domain.log](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/files/10105754/CDP4IME.-.v2.Crash.after.publication.of.state.dependent.parameters.from.Armament.domain.log)

### System Configuration

- COMET version:
  - [x] COMET-IME: 9.3.0.1
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4/COMET Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by lxatstariongroup** [comment]
@samatstariongroup @MartinFijneman Not reproducible. Seems like the same behavior we have seen and fixed before in #1264.
