### ISSUE TITLE
Crash upon creating various review items

### ISSUE THREAD

**Issue by gwenatrhea** [STARIONGROUP/COMET-IME-Community-Edition#1202]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of the COMET-IME
- [ ] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

when right clicking the element definition, the functions add review item discrepancy, request for waiver, request for deviation and change request all result in crashing the app. Same happens in the requirements specification when creating these items

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [ ] COMET-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4/COMET Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by lxatstariongroup** [comment]
Does not work, but also does not crash anymore. Dialogs are not registered for review items.
@samatstariongroup what to do with this particular issue?

**Comment by lxatstariongroup** [comment]
Decided to remove non-working review components in the IME.
