### ISSUE TITLE
Model tab- opening Error browser leads to crash of COMET

### ISSUE THREAD

**Issue by MartinFijneman** [STARIONGROUP/COMET-IME-Community-Edition#1208]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [ ] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

testing on DEV-server
in engineering model, copied 2 element definitions from engineering model " Types Testing" to engineering model "20221216 dotnet6 zip-versie"
* All Parameter Types - With Values
* All Parameter Types - With Values - With Subscriptions

The  parameter types, with values, with subscriptions in the EM "Types Testing" apparently has an issue, has several components indicated in red. only noticed this after copying action.

![reference version 9 3 - test array with errors on components](https://user-images.githubusercontent.com/35371313/208916920-d0ba2326-ac5b-4a07-a465-1c4d1b45b7b0.PNG)

Trying to inspect, opened the error browser through the model-tab > model verification

In the reference 9.3 version (on own laptop), this was ok, opening the Error browser

in the dotnet 6 version, trying to open this view leads to a crash of the application, disappearing without any exception.

reproducible, not depending on specific server/ model: reproduced on public server with loft model

### Steps to Reproduce

with dotnet 6 testing version, open any model
go to the model tab
open the Error browser > IME crashes

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [x] COMET-IME: dotnet6 testing zip file, received 20221221 11:56
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4/COMET Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by lxatstariongroup** [comment]
Specific problem with Array properties was already solved. Error in Error Browser that leads to the crash is not reproducible anymore.
