### ISSUE TITLE
Create new iteration in client A leads to problems and potential crash in client B - iteration process needs better handling

### ISSUE THREAD

**Issue by MartinFijneman** [STARIONGROUP/COMET-IME-Community-Edition#1219]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [ ] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

iterations - create new iteration needs better handling in other clients
* when  a new iteration was created in client A, client B element definitions browser turns "white" when the update arrives
* not clear how, but in testing, for Gwen in client B on the model tab, for the element definitions browser selection, an "iteration 0"showed up > selecting this causes crash of IME

NOTE: general issue, do not expect this issue to be related to dotnet 6 version, but not yet completely investigated on reference version 9.3
posted now as general issue

### Steps to Reproduce

multi-client test, client A to create new iterations, client B with domain expert participant to get in updates for new iteration

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [x] COMET-IME: dotnet 6 version 20221221 15:30, although expected to be relevant to reference version 9.3 as well
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4/COMET Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by samatrhea** [comment]
to resolve:

- [ ] create test setup with a local server to reproduce
- [ ] fix view associated viewmodel
- [ ] update unit tests to achieve at least 80% on new code

**Comment by lxatstariongroup** [comment]
Crash does not happen anymore, but Iteration 0 indeed appears. Needs further investigation to find the exact cause. Seems IME related, not server.

**Comment by lxatstariongroup** [comment]
Server side we are able to edit elements of the "old" frozen Iteration and probably the return message of that one creates the white screen: No Elements contained by the old frozen iteration which is indeed the case from a database perspective.
The server should not updates to frozen Iterations.
