### ISSUE TITLE
[bug] [CDF] [IME] COMET IME crashing when closing Element Definitions Browser after attempting to delete parameter subscription

### ISSUE THREAD

**Issue by JustinBourgois** [STARIONGROUP/COMET-IME-Community-Edition#1247]
### Prerequisites

- [X] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of the COMET-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When attempting to delete a parameter subscription, the change did not take effect. The subscription symbol was still visible and right click -> Edit opened the subscription editor. When closing the Element Definitions Browser COMET froze for a while and then crashed, the first time without an error message, and the second time this happened the following message was displayed:

![Error message](https://user-images.githubusercontent.com/49306917/232063439-19dcd102-10f3-43d3-a748-a4f7033017d6.PNG)

### Steps to Reproduce
Delete a parameter subscription from the Element Definitions Browser. If subscription symbol remains and editing the parameter opens the element subscription editor, then close the Element Definitions Browser. This will usually result in COMET becoming unresponsive and sometimes lead to crashing.

### Logs

  - [X] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [X] COMET-IME: 
  - [ ] Other: 
  - 9.2.0.7
- Web Services:
  - [X] CDP4/COMET Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [X] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by lxatrhea** [comment]
We have tried to reproduce this, but so far we were not able to do so.
@JustinBourgois Could you provide use the COMET server logs from around the time that removing the subscription did not perform as expected?

**Comment by lxatstariongroup** [comment]
Not reproducible anymore in version 10.0.0
