### ISSUE TITLE
Unsubscribing from parameters does not seem to take effect without closing the element definitions browser

### ISSUE THREAD

**Issue by samatstariongroup** [STARIONGROUP/COMET-IME-Community-Edition#1263]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Unsubscribing from parameters does not appear to take effect without closing the element definitions browser

### Steps to Reproduce

1. open a model and subscribe to a parameter that  is owned by another DoE
2. close COMET and restart
3. unsubscribe and verify that it does not seem to take effect in the ElementDef browser
4. close and open browser to see that subscription is no longer present in the browser

### Logs

  - [x] There are no logs regarding the issue
  
### System Configuration

- COMET version:
  - [x] COMET-IME: 9.5

**Comment by lxatstariongroup** [comment]
Not reproducible anymore in version 10.0.0-RC11
