### ISSUE TITLE
Open new engineering model - doesn't open new model based on source model

### ISSUE THREAD

**Issue by meritvdlee** [STARIONGROUP/COMET-IME-Community-Edition#1294]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

After creating a new engineering model based on a source model it doesn't open the new model. Opening a new model does work for models that are not created from a source model.

![image](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/assets/142905459/9a27ffaa-a81f-4e33-b8f2-b4339ceb433c)

### Steps to Reproduce

Create a new engineering model from a source model and only fill in the short name, name and source model. (see image in description).

### Logs

The data-source replied with code InternalServerError: Internal Server Error

  - [ ] There are no logs regarding the issue
  - [x] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- COMET version:
  - [ ] COMET-IME: 9.6.01
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4/COMET Web Services version: 8.0.0-rc7
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): Windows 11 Enterprise, 64 bit
  - [ ] Additional information:

**Comment by lxatstariongroup** [comment]
Not reproducible. Might be that the source Model had some incompatibility in DomainOfExpertises.
