### ISSUE TITLE
Export Engineering model does not work when initiated from the Models browser

### ISSUE THREAD

**Issue by IevhenIkonnykov** [STARIONGROUP/COMET-IME-Community-Edition#219]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When a user attempts to export a model nothing happens - no export, no errors.

### Steps to Reproduce
Open IME, connect to a server, open an iteration, go to the Directory tab, open Models window, choose a model and try to export it by clicking "Export Engineering Model Setup" button.

### Logs
Logger: CDP4EngineeringModel.ViewModels.ModelSelectionSessionRowViewModel
Message: Export Command called
Log LEvel: Info

  - [ ] There are no logs regarding the issue
  - [ ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME:  4.0.3.0
  - [ ] Other: 
  -
- Web Services:
  - [x] CDP4 Web Services version: latest on the issue date
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [x] Windows OS (32/64 bit): 64bit
  - [ ] Additional information:

**Comment by samatrhea** [comment]
Would be interesting to make use of the server API to export the model. We have to make sure that when the model is exported, the permission handling is taken into account.

The current export functionality (when called from the home tab on the Ribbon) exports the in-memory engineering-model. When calling the function from the model-browser, then the data is not necessarily loaded in the IME and we can only rely on the server.

**Comment by IevhenIkonnykov** [comment]
During my investigation I only used export using server API and I can say for sure if a user does not have a permission for a model it tries to export then an error is thrown (it was not obvious, so I updated this error handling on the server to be more clear). Is that what you mean?

**Comment by samatrhea** [comment]
in part yes, but what i mean is that the content of the exported model respects the permission handling. So, if you don;'t have read on Requirements, requirements are not returned. So the point is, lets make sure that by using the export API you cannot get more data than using the regular REST API

**Comment by IevhenIkonnykov** [comment]
I see, then we need to craft some test model and prepare an integration test for this.
