### ISSUE TITLE
Missing LanguageCode in ReqIf import

### ISSUE THREAD

**Issue by lxatstariongroup** [STARIONGROUP/COMET-IME-Community-Edition#996]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the COMET-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Missing LanguageCode during ReqIf import.

Fix in SDK: Default value on LanguageCode => en-GB

### Steps to Reproduce
- Start process via "Requirements/ReqIF->Import"
- Select model and correct ReqIF file
- Select auto for mapping
- In the next window, the following parameter types are shown: Integer, String, Date, Created Thru (with suptypes: Manual Input, Extracting, Copying), Text, Boolean
  - Based on my COMET ReqIF roundtrip experience I only map Text (to "text") and Boolean (to "boolean") since there is no clear mapping available for the other types
  - For String one could use text and for date there are multiple different options
 ![doors_simple_datatypes](https://user-images.githubusercontent.com/93251855/139081655-4d1aadba-a941-46b7-87d5-7c2a2d464704.png)

- Next, the specification parameters are mapped: ReqIF.ForeignCreatedBy, ReqIF.ForeignCreatedOn, ReqIF.Description, ReqIF.ForeignModifiedBy, ReqIF.ForeignModifiedOn, ReqIF.Name, ReqIF.Prefix
  - Assign ReqIF.Description to FIRST_DEFINITION
  - Assign ReqIF.Name to NAME (because I know from the ReqIF file that the name has whitespace which is not valid for the COMET shortname)
  - For the others, clear mapping is available so they are mapped to NONE (options are: NONE, SHORTNAME, NAME, FIRST_DEFINITION, PARAMETER_VALUE)
  - **This could be a potential error source since there is no mapping to SHORTNAME**
![doors_simple_specification](https://user-images.githubusercontent.com/93251855/139081760-7741db12-00b1-48ff-8d7e-341dbf90b17c.png)

- Next, the requirement parameters are mapped: ReqIF.ForeignID, ReqIF.ForeignCreatedBy, ReqIF.ForeignCreatedOn, ReqIF.CreatedThru, ReqIF.ForeignModifiedBy, ReqIF.ForeignModifiedOn, ReqIF.ChapterName, ReqIF.Name, ReqIF.Text, ReqIF.ForeignDeleted
  - ReqIF.ChapterName is mapped to SHORTNAME
  - ReqIF.Name is mapped to NAME
  - ReqIF.Text is mapped to FIRST_DEFINITION
  - **Again, here I am aware that the naming rules in DOORS for chapter and name do not correspond to the ones in COMET. Yet, it is the only mapping that makes sense to me**
![doors_simple_requirements](https://user-images.githubusercontent.com/93251855/139081789-03d8bac4-d93a-4b93-8e92-0c68b1d1ddf1.png)

- In the next window, Relation-Groups are defined. I don't have any.
- In the next window, Spec-Relations are defined. I don't have any.
- In the next window, I can see a preview of the import. 
  - Name, shortname, and definition are filled with the xhtml value of the corresponding ReqIF Attribute definition
![doors_simple_preview](https://user-images.githubusercontent.com/93251855/139081807-5f48c995-099e-46c2-9446-924575dba81e.png)

- When clicking OK, the following error is raised: 
  - `The CDP4 Services replied with code InternalServerError: Internal Server Error: "exception:The \u0027LanguageCode\u0027 property of a \u0027Definition\u0027 is mandatory and cannot be empty or null.`

#### EXAMPLE REQIF FILE
The used example reqif file is attached as .txt. Rename file extension to .reqif before import.
[COMET_EXPORT_TEST_1.txt](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/files/7426797/COMET_EXPORT_TEST_1.txt)

  - [x] There are no logs regarding the issue
  - [ ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration
- COMET version:
  - [x] COMET-IME: 9.0.1.1
  - [ ] Other: 
  -
- Web Services:
  - [x] CDP4/COMET Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [x] Windows OS (32/64 bit): 64
  - [ ] Additional information:

**Comment by dubowym** [comment]
Has this been solved in the meanwhile? I am stuck with the same error.

**Comment by samatrhea** [comment]
is it possible to share a reqif file so we can reproduce?

**Comment by dubowym** [comment]
[out.txt](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/files/14918551/out.txt)
File attached. The problem seems to be with the language code of the requirement definition. If I omit the requirement definition (requirement text), the file can be imported.

**Comment by dubowym** [comment]
Hi, any hints how this problem could be solved? I am about to start adding 400 requirement definitions manually.

**Comment by lxatstariongroup** [comment]
Dear @dubowym,

The solution is simple in COMET, but I cannot create a fast update for you. 
Problem is that there is no fallback languagecode defined if the reqif file does not contain a value for that.
In the reqif file there should be a header where the reqif language code can be found.
I propose you edit the reqif file manually:

<REQ-IF xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" **xml:lang="en"** xmlns="http://www.omg.org/spec/ReqIF/20110401/reqif.xsd">

The part that is missing in the reqif file is **xml:lang="en"**.
If you add **only that specific part** manually to the existing header, I think it should work in your case.

The problem will be solved in the next official COMET release.

Best regards,
@lxatstariongroup

**Comment by dubowym** [comment]
Dear @lxatstariongroup,

thanks a lot for providing the work-around. It solved the problem and saved me a lot of time.

Best Regards,
@dubowym
